// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiV1TaskItemsByIdData, DeleteApiV1TaskItemsByIdResponses, DeleteApiV1TaskItemsByTaskIdNotesByIdData, DeleteApiV1TaskItemsByTaskIdNotesByIdResponses, GetApiV1TaskItemsByTaskIdNotesData, GetApiV1TaskItemsByTaskIdNotesResponses, GetApiV1TaskItemsData, GetApiV1TaskItemsResponses, GetNoteV1Data, GetNoteV1Responses, GetTaskV1Data, GetTaskV1Responses, PostApiV1TaskItemsByTaskIdNotesData, PostApiV1TaskItemsByTaskIdNotesResponses, PostApiV1TaskItemsData, PostApiV1TaskItemsResponses, PutApiV1TaskItemsByIdData, PutApiV1TaskItemsByIdResponses, PutApiV1TaskItemsByTaskIdNotesByIdData, PutApiV1TaskItemsByTaskIdNotesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiV1TaskItemsByTaskIdNotes = <ThrowOnError extends boolean = false>(options: Options<GetApiV1TaskItemsByTaskIdNotesData, ThrowOnError>) => (options.client ?? client).get<GetApiV1TaskItemsByTaskIdNotesResponses, unknown, ThrowOnError>({ url: '/api/v1/TaskItems/{taskId}/notes', ...options });

export const postApiV1TaskItemsByTaskIdNotes = <ThrowOnError extends boolean = false>(options: Options<PostApiV1TaskItemsByTaskIdNotesData, ThrowOnError>) => (options.client ?? client).post<PostApiV1TaskItemsByTaskIdNotesResponses, unknown, ThrowOnError>({
    url: '/api/v1/TaskItems/{taskId}/notes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiV1TaskItemsByTaskIdNotesById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1TaskItemsByTaskIdNotesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiV1TaskItemsByTaskIdNotesByIdResponses, unknown, ThrowOnError>({ url: '/api/v1/TaskItems/{taskId}/notes/{id}', ...options });

export const getNoteV1 = <ThrowOnError extends boolean = false>(options: Options<GetNoteV1Data, ThrowOnError>) => (options.client ?? client).get<GetNoteV1Responses, unknown, ThrowOnError>({ url: '/api/v1/TaskItems/{taskId}/notes/{id}', ...options });

export const putApiV1TaskItemsByTaskIdNotesById = <ThrowOnError extends boolean = false>(options: Options<PutApiV1TaskItemsByTaskIdNotesByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiV1TaskItemsByTaskIdNotesByIdResponses, unknown, ThrowOnError>({
    url: '/api/v1/TaskItems/{taskId}/notes/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiV1TaskItems = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1TaskItemsData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1TaskItemsResponses, unknown, ThrowOnError>({ url: '/api/v1/TaskItems', ...options });

export const postApiV1TaskItems = <ThrowOnError extends boolean = false>(options: Options<PostApiV1TaskItemsData, ThrowOnError>) => (options.client ?? client).post<PostApiV1TaskItemsResponses, unknown, ThrowOnError>({
    url: '/api/v1/TaskItems',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiV1TaskItemsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1TaskItemsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiV1TaskItemsByIdResponses, unknown, ThrowOnError>({ url: '/api/v1/TaskItems/{id}', ...options });

export const getTaskV1 = <ThrowOnError extends boolean = false>(options: Options<GetTaskV1Data, ThrowOnError>) => (options.client ?? client).get<GetTaskV1Responses, unknown, ThrowOnError>({ url: '/api/v1/TaskItems/{id}', ...options });

export const putApiV1TaskItemsById = <ThrowOnError extends boolean = false>(options: Options<PutApiV1TaskItemsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiV1TaskItemsByIdResponses, unknown, ThrowOnError>({
    url: '/api/v1/TaskItems/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
