// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};

export type CreateNoteDto = {
    content: string;
};

export type CreateTaskItemDto = {
    title?: string;
    description?: null | string;
    status?: Status;
    isComplete?: boolean;
    priority?: Priority;
    dueDate?: null | string;
};

export type NoteResponseDto = {
    id?: number | string;
    content: string;
    taskItemId?: number | string;
    createdAt?: string;
    updatedAt?: null | string;
};

export type Priority = 'low' | 'medium' | 'high';

export type Status = 'draft' | 'todo' | 'completed';

export type TaskItemResponseDto = {
    id?: number | string;
    title: string;
    description?: null | string;
    isComplete?: boolean;
    dueDate?: null | string;
    status?: string;
    priority?: string;
};

export type UpdateNoteDto = {
    content: string;
};

export type UpdateTaskItemDto = {
    title?: string;
    description?: null | string;
    status?: null | Status;
    isComplete?: boolean;
    priority?: null | Priority;
    dueDate?: null | string;
};

export type GetApiV1TaskItemsByTaskIdNotesData = {
    body?: never;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/v1/TaskItems/{taskId}/notes';
};

export type GetApiV1TaskItemsByTaskIdNotesResponses = {
    /**
     * OK
     */
    200: Array<NoteResponseDto>;
};

export type GetApiV1TaskItemsByTaskIdNotesResponse = GetApiV1TaskItemsByTaskIdNotesResponses[keyof GetApiV1TaskItemsByTaskIdNotesResponses];

export type PostApiV1TaskItemsByTaskIdNotesData = {
    body: CreateNoteDto;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/v1/TaskItems/{taskId}/notes';
};

export type PostApiV1TaskItemsByTaskIdNotesResponses = {
    /**
     * OK
     */
    200: NoteResponseDto;
};

export type PostApiV1TaskItemsByTaskIdNotesResponse = PostApiV1TaskItemsByTaskIdNotesResponses[keyof PostApiV1TaskItemsByTaskIdNotesResponses];

export type DeleteApiV1TaskItemsByTaskIdNotesByIdData = {
    body?: never;
    path: {
        taskId: number | string;
        id: number | string;
    };
    query?: never;
    url: '/api/v1/TaskItems/{taskId}/notes/{id}';
};

export type DeleteApiV1TaskItemsByTaskIdNotesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetNoteV1Data = {
    body?: never;
    path: {
        taskId: number | string;
        id: number | string;
    };
    query?: never;
    url: '/api/v1/TaskItems/{taskId}/notes/{id}';
};

export type GetNoteV1Responses = {
    /**
     * OK
     */
    200: NoteResponseDto;
};

export type GetNoteV1Response = GetNoteV1Responses[keyof GetNoteV1Responses];

export type PutApiV1TaskItemsByTaskIdNotesByIdData = {
    body: UpdateNoteDto;
    path: {
        taskId: number | string;
        id: number | string;
    };
    query?: never;
    url: '/api/v1/TaskItems/{taskId}/notes/{id}';
};

export type PutApiV1TaskItemsByTaskIdNotesByIdResponses = {
    /**
     * OK
     */
    200: NoteResponseDto;
};

export type PutApiV1TaskItemsByTaskIdNotesByIdResponse = PutApiV1TaskItemsByTaskIdNotesByIdResponses[keyof PutApiV1TaskItemsByTaskIdNotesByIdResponses];

export type GetApiV1TaskItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/TaskItems';
};

export type GetApiV1TaskItemsResponses = {
    /**
     * OK
     */
    200: Array<TaskItemResponseDto>;
};

export type GetApiV1TaskItemsResponse = GetApiV1TaskItemsResponses[keyof GetApiV1TaskItemsResponses];

export type PostApiV1TaskItemsData = {
    body: CreateTaskItemDto;
    path?: never;
    query?: never;
    url: '/api/v1/TaskItems';
};

export type PostApiV1TaskItemsResponses = {
    /**
     * OK
     */
    200: TaskItemResponseDto;
};

export type PostApiV1TaskItemsResponse = PostApiV1TaskItemsResponses[keyof PostApiV1TaskItemsResponses];

export type DeleteApiV1TaskItemsByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/v1/TaskItems/{id}';
};

export type DeleteApiV1TaskItemsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTaskV1Data = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/v1/TaskItems/{id}';
};

export type GetTaskV1Responses = {
    /**
     * OK
     */
    200: TaskItemResponseDto;
};

export type GetTaskV1Response = GetTaskV1Responses[keyof GetTaskV1Responses];

export type PutApiV1TaskItemsByIdData = {
    body: UpdateTaskItemDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/v1/TaskItems/{id}';
};

export type PutApiV1TaskItemsByIdResponses = {
    /**
     * OK
     */
    200: TaskItemResponseDto;
};

export type PutApiV1TaskItemsByIdResponse = PutApiV1TaskItemsByIdResponses[keyof PutApiV1TaskItemsByIdResponses];
