name: Build and Deploy TaskFlow API (.NET 9)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write      # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskFlow.Api/TaskFlow.Api.csproj

      - name: Build
        run: dotnet build TaskFlow.Api/TaskFlow.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish TaskFlow.Api/TaskFlow.Api.csproj -c Release -o ./publish

      - name: Azure Login (using Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push container image
        run: |
          docker build -t taskflowapi9 .
          docker tag taskflowapi9 ${{ secrets.ACR_LOGIN_SERVER }}/taskflowapi9:latest
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/taskflowapi9:latest

      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/taskflowapi9:latest
