name: Deploy to Azure Production

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: TaskFlowRG
  WEBAPP_NAME: taskflowapi2074394909
  ACR_NAME: taskflowregistry
  ACR_IMAGE_NAME: taskflowapi9

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image to ACR
        run: |
          az acr build \
            --registry ${{ env.ACR_NAME }} \
            --image ${{ env.ACR_IMAGE_NAME }}:latest \
            --image ${{ env.ACR_IMAGE_NAME }}:${{ github.sha }} \
            --file TaskFlow.Api/Dockerfile \
            .

      - name: Enable system-assigned identity
        run: |
          az webapp identity assign \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.WEBAPP_NAME }}

      - name: Get webapp managed identity principal ID
        id: get_principal
        run: |
          principalId=$(az webapp show \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.WEBAPP_NAME }} \
            --query identity.principalId -o tsv)
          echo "PRINCIPAL_ID=$principalId" >> $GITHUB_ENV

      - name: Grant AcrPull role to webapp identity
        continue-on-error: true
        run: |
          az role assignment create \
            --assignee ${{ env.PRINCIPAL_ID }} \
            --role AcrPull \
            --scope $(az acr show --name ${{ env.ACR_NAME }} --query id -o tsv)

      - name: Configure webapp to use managed identity for ACR
        run: |
          az resource update \
            --ids /subscriptions/$(az account show --query id -o tsv)/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.Web/sites/${{ env.WEBAPP_NAME }}/config/web \
            --set properties.acrUseManagedIdentityCreds=true

      - name: Set the container image
        run: |
          az webapp config container set \
            --name ${{ env.WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --container-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_IMAGE_NAME }}:latest \
            --container-registry-url https://${{ env.ACR_NAME }}.azurecr.io

      - name: Restart webapp
        run: |
          az webapp restart \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.WEBAPP_NAME }}