name: Build and Deploy TaskFlow API

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskFlow.Api/TaskFlow.Api.csproj

      - name: Build
        run: dotnet build TaskFlow.Api/TaskFlow.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish TaskFlow.Api/TaskFlow.Api.csproj -c Release -o ./publish

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
