name: Build and Deploy TaskFlow API (.NET 9)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image to ACR
        run: |
          az acr build \
            --registry taskflowregistry \
            --image taskflowapi9:latest \
            --image taskflowapi9:${{ github.sha }} \
            --file TaskFlow.Api/Dockerfile \
            .

      - name: Enable system-assigned identity
        run: |
          az webapp identity assign \
            --resource-group TaskFlowRG \
            --name taskflowapi2074394909

      - name: Get webapp managed identity principal ID
        id: get_principal
        run: |
          principalId=$(az webapp show \
            --resource-group TaskFlowRG \
            --name taskflowapi2074394909 \
            --query identity.principalId -o tsv)
          echo "PRINCIPAL_ID=$principalId" >> $GITHUB_ENV
          echo "Principal ID: $principalId"

      - name: Grant AcrPull role to webapp identity
        continue-on-error: true
        run: |
          az role assignment create \
            --assignee ${{ env.PRINCIPAL_ID }} \
            --role AcrPull \
            --scope /subscriptions/b615d287-669e-4541-9623-2cc0093c487a/resourceGroups/TaskFlowRG/providers/Microsoft.ContainerRegistry/registries/taskflowregistry
          echo "Role assignment step completed (may already exist)"

      - name: Configure webapp to use managed identity for ACR
        run: |
          az resource update \
            --ids /subscriptions/b615d287-669e-4541-9623-2cc0093c487a/resourceGroups/TaskFlowRG/providers/Microsoft.Web/sites/taskflowapi2074394909/config/web \
            --set properties.acrUseManagedIdentityCreds=true

      - name: Set the container image
        run: |
          az webapp config container set \
            --name taskflowapi2074394909 \
            --resource-group TaskFlowRG \
            --container-image-name taskflowregistry.azurecr.io/taskflowapi9:latest \
            --container-registry-url https://taskflowregistry.azurecr.io

      - name: Restart webapp
        run: |
          az webapp restart \
            --resource-group TaskFlowRG \
            --name taskflowapi2074394909