name: Build and Deploy TaskFlow API (.NET 9)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write      # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskFlow.Api/TaskFlow.Api.csproj

      - name: Build
        run: dotnet build TaskFlow.Api/TaskFlow.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish TaskFlow.Api/TaskFlow.Api.csproj -c Release -o ./publish

      - name: Azure Login (using Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable system-assigned identity and get the principal ID
        id: enable_identity
        run: |
          principalId=$(az webapp identity assign --resource-group TaskFlowRG --name taskflowapi2074394909 --query principalId -o tsv)
          echo "PRINCIPAL_ID=$principalId" >> $GITHUB_ENV

      - name: Get the ACR resource ID
        id: get_acr_id
        run: |
          acrId=$(az acr show -n taskflowregistry --query id -o tsv)
          echo "ACR_ID=$acrId" >> $GITHUB_ENV

      - name: Grant webapp identity AcrPull on the registry
        run: az role assignment create --assignee ${{ env.PRINCIPAL_ID }} --role AcrPull --scope ${{ env.ACR_ID }}

      - name: Set the container image
        run: |
          az webapp config container set \
            --name taskflowapi2074394909 \
            --resource-group TaskFlowRG \
            --container-image-name taskflowregistry.azurecr.io/taskflowapi9:latest \
            --container-registry-url https://taskflowregistry.azurecr.io
