name: Build and Deploy TaskFlow API (.NET 9)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write      # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskFlow.Api/TaskFlow.Api.csproj

      - name: Build
        run: dotnet build TaskFlow.Api/TaskFlow.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish TaskFlow.Api/TaskFlow.Api.csproj -c Release -o ./publish

      - name: Azure Login (using Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable system-assigned identity
        run: |
          az webapp identity assign \
            --resource-group TaskFlowRG \
            --name taskflowapi2074394909

      - name: Get webapp managed identity principal ID
        id: get_principal
        run: |
          principalId=$(az webapp show \
            --resource-group TaskFlowRG \
            --name taskflowapi2074394909 \
            --query identity.principalId -o tsv)
          echo "PRINCIPAL_ID=$principalId" >> $GITHUB_ENV
          echo "Principal ID: $principalId"

      - name: Grant AcrPull role to webapp identity
        run: |
          az role assignment create \
            --assignee ${{ env.PRINCIPAL_ID }} \
            --role AcrPull \
            --scope /subscriptions/b615d287-669e-4541-9623-2cc0093c487a/resourceGroups/TaskFlowRG/providers/Microsoft.ContainerRegistry/registries/taskflowregistry \
            || echo "Role assignment may already exist"

      - name: Configure webapp to use managed identity for ACR
        run: |
          az webapp config set \
            --resource-group TaskFlowRG \
            --name taskflowapi2074394909 \
            --generic-configurations '{"acrUseManagedIdentityCreds": true}'

      - name: Set the container image
        run: |
          az webapp config container set \
            --name taskflowapi2074394909 \
            --resource-group TaskFlowRG \
            --container-image-name taskflowregistry.azurecr.io/taskflowapi9:latest \
            --container-registry-url https://taskflowregistry.azurecr.io

      - name: Restart webapp
        run: |
          az webapp restart \
            --resource-group TaskFlowRG \
            --name taskflowapi2074394909
