name: Build and Deploy TaskFlow API (.NET 9)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write      # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskFlow.Api.csproj

      - name: Build
        run: dotnet build TaskFlow.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish TaskFlow.Api.csproj -c Release -o ./publish

      - name: Azure Login (using Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./publish
